### ISSUE TITLE
wrong OS listed when rendering Quarto

### ISSUE THREAD

**Issue by hueyrb** [r-lib/sessioninfo#79] opened 2022-11-11 15:41 UTC
quarto document lists wrong os
Running sessioninfo * 1.2.2 on mac with Ventura 13.0.1
when I run this script in the console or click on the green triangle in the source panel, I get the correct os:

sessioninfo::session_info(pkgs = "attached")

version  R version 4.2.1 (2022-06-23)
 os       macOS Ventura 13.0.1
 system   x86_64, darwin17.0
 ui       RStudio

but when I Render my Quarto document I get 

version  R version 4.2.1 (2022-06-23)
 os       macOS Big Sur ... 10.16
 system   x86_64, darwin17.0
 ui       X11

Note that the ui = Rstudio works, but ui = X11 does not.

**Comment by gaborcsardi** [comment] 2022-11-11 15:55
What do you get with `utils::sessionInfo()`?

**Comment by hueyrb** [comment] 2022-11-11 16:03
thanks for getting back!

> utils::sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK:
/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets
[6] methods   base

loaded via a namespace (and not attached):
 [1] httr_1.4.4          tidyr_1.2.1
 [3] bit64_4.0.5         vroom_1.6.0
 [5] viridisLite_0.4.1   splines_4.2.1
 [7] here_1.0.1          Formula_1.2-4
 [9] assertthat_0.2.1    latticeExtra_0.6-30
[11] sessioninfo_1.2.2   pillar_1.8.1
[13] backports_1.4.1     lattice_0.20-45
[15] glue_1.6.2          digest_0.6.29
[17] RColorBrewer_1.1-3  checkmate_2.1.0
[19] rvest_1.0.3         colorspace_2.0-3
[21] htmltools_0.5.3     Matrix_1.5-1
[23] pkgconfig_2.0.3     purrr_0.3.5
[25] scales_1.2.1        webshot_0.5.4
[27] svglite_2.1.0       jpeg_0.1-9
[29] tzdb_0.3.0          htmlTable_2.4.1
[31] tibble_3.1.8        mgcv_1.8-40
[33] generics_0.1.3      ggplot2_3.3.6
[35] pacman_0.5.1        nnet_7.3-18
[37] cli_3.4.1           survival_3.4-0
[39] magrittr_2.0.3      crayon_1.5.2
[41] deldir_1.0-6        evaluate_0.17
[43] fansi_1.0.3         nlme_3.1-160
[45] MASS_7.3-58.1       xml2_1.3.3
[47] foreign_0.8-83      vegan_2.6-4
[49] tools_4.2.1         data.table_1.14.2
[51] lifecycle_1.0.3     stringr_1.4.1
[53] interp_1.1-3        munsell_0.5.0
[55] cluster_2.1.4       kableExtra_1.3.4
[57] compiler_4.2.1      systemfonts_1.0.4
[59] rlang_1.0.6         grid_4.2.1
[61] rstudioapi_0.14     htmlwidgets_1.5.4
[63] base64enc_0.1-3     rmarkdown_2.17
[65] gtable_0.3.1        DBI_1.1.3
[67] R6_2.5.1            gridExtra_2.3
[69] knitr_1.40          dplyr_1.0.10
[71] fastmap_1.1.0       bit_4.0.4
[73] utf8_1.2.2          Hmisc_4.7-1
[75] rprojroot_2.0.3     permute_0.9-7
[77] stringi_1.7.8       parallel_4.2.1
[79] Rcpp_1.0.9          vctrs_0.4.2
[81] rpart_4.1.16        png_0.1-7
[83] tidyselect_1.1.2    xfun_0.33

**Comment by gaborcsardi** [comment] 2022-11-11 16:08
This is from Quarto?

**Comment by hueyrb** [comment] 2022-11-11 16:22
I'd run the command you sent in the console.
To see what happens when I ran it in the Rstudio source panel,
I just loaded the base Quarto document, and added the utils..., and
rendered it (see below)
```{r}
utils::sessionInfo()
```
and it is giving Big Sur, not Ventura.

[image: image.png]
----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-11 16:36
> and it is giving Big Sur, not Ventura.

I am afraid that this is an issue in `utils::sessionInfo()` then, as sessioninfo uses `utils::sessionInfo("base")$running`.

**Comment by hueyrb** [comment] 2022-11-11 17:04
Hi Gábor,

If I run utils::sessionInfo()  in the R app, I get Ventura

if I run utils::sessionInfo()  in the console in Rstudio, I get Ventura

But if I run a qmd file OR a rmd file from within Rstudio, it gives Big Sur.

Ray

**Comment by gaborcsardi** [comment] 2022-11-11 17:38
I cannot reproduce this on an arm mac. Can you please copy and paste the output of `utils::sessionInfo()` and also `osVersion`, from within quarto? Thanks.

**Comment by hueyrb** [comment] 2022-11-11 17:39
Hi again, Gábor,

I just found this link -- someone previously had the same problem, but was
a windows user.

https://github.com/r-lib/sessioninfo/issues/76

I'll try to report a bug to base R, as you suggested.  If I get a
resolution, I'll let you know.

Thanks for helping
Ray

----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-11 17:40
I am fairly sure that that's a different problem.

**Comment by hueyrb** [comment] 2022-11-11 17:45
I'll send two versions.  The first is when I run utils::sessionInfo() in
the source panel of Rstudio (clicking on green triangle).

#########
> utils::sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK:
/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets
[6] methods   base

loaded via a namespace (and not attached):
 [1] compiler_4.2.1   fastmap_1.1.0
 [3] rsconnect_0.8.28 cli_3.4.1
 [5] htmltools_0.5.3  tools_4.2.1
 [7] rstudioapi_0.14  yaml_2.3.5
 [9] rmarkdown_2.17   knitr_1.40
[11] xfun_0.33        digest_0.6.29
[13] rlang_1.0.6      evaluate_0.17

Here's the htmal output when I render in Quarto

utils::sessionInfo()

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] digest_0.6.29     jsonlite_1.8.2    magrittr_2.0.3    evaluate_0.17
 [5] rlang_1.0.6       stringi_1.7.8     cli_3.4.1         rstudioapi_0.14
 [9] rmarkdown_2.17    tools_4.2.1       stringr_1.4.1     htmlwidgets_1.5.4
[13] xfun_0.33         yaml_2.3.5        fastmap_1.1.0     compiler_4.2.1
[17] htmltools_0.5.3   knitr_1.40

----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-11 17:53
Thanks! What do you get if you run it from a terminal? Property terminal, not rstudio terminal.

**Comment by hueyrb** [comment] 2022-11-11 18:07
I ran quarto render test.qmd
and the output still shows Big Sur
curiously, it no longer shows the 'ui' listing -- Rstudio when gives
correct OS, X11 when giving Big Sur

but I just ran sessioninfo::...  in the console in Rstudio and got this.

> sessioninfo::session_info(pkgs = "attached")
Error in data.frame(package = x$package, `*` = ifelse(x$attached, "*",  :
  arguments imply differing number of rows: 0, 1
>

XQuartz is new XQuartz 2.8.2 (xorg-server 1.20.14)

[image: image.png]
----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-13 08:26
Sorry, I meant running `utils::sessionInfo()` in a macOS terminal, without quarto.

**Comment by hueyrb** [comment] 2022-11-13 18:02
HI Gábor,

when I run that in the terminal I get
function>

I found this on stackoverflow:
https://stackoverflow.com/questions/73746067/different-sessioninfo-output-on-mac-cli-vs-rstudio

Looks like the same problem.  I tried updating Rstudio and r (I had 4.2.1,
now 4.2.2) restarted my computer, and still shows Big Sur when
I render a qmd file.
Also set up a new Rmd file -- gives Big Sur

I can live with this by some quick-and-dirty procedures.  I
ran  utils::sessionInfo()  in the console, and copied and pasted the output
above packages into the qmd file (as text).
then added:    sessioninfo::session_info(info = "packages")  to the source
pane.
when I render, I have the correct OS info and the packages.

Thanks very much for trying to help.

Ray




----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-13 18:38
I don't think that that answer is correct, `utils::osVersion` is set when the utils package is loaded, at least since 2018:
https://github.com/wch/r-source/blob/d75369598258c236055bcc7722c32189cb899ca6/src/library/utils/R/zzz.R#L67

OTOH there seems to be a bug in the x86_64 builds:
```
❯ R-4.2 -q -e utils::osVersion
> utils::osVersion
[1] "macOS Big Sur ... 10.16"
```

The arm builds seem fine:
```
❯ R-4.2-arm64 -q -e utils::osVersion
> utils::osVersion
[1] "macOS Monterey 12.6.1"
```

This is unfortunate. Maybe we should work around it in sessioninfo, I'll think about it.

**Comment by hueyrb** [comment] 2022-11-13 18:42
OK, thanks for the clarification.  Please let me know if you figure
anything out.

Ray

----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-13 18:48
Well, it basically comes down to macOS supplying different information to the x86_64 build of R:
```
❯ R-4.2 -q -e 'readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]'
> readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]
[1] "\t<key>ProductUserVisibleVersion</key>"
[2] "\t<string>10.16</string>"
```

```
❯ R-4.2-arm64 -q -e 'readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]'
> readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]
[1] "\t<key>ProductUserVisibleVersion</key>"
[2] "\t<string>12.6.1</string>"
```

**Comment by gaborcsardi** [comment] 2022-11-13 18:52
This works:
```
❯ R-4.2 -q -e 'system("cat /System/Library/CoreServices/SystemVersion.plist | grep -A 1 ProductUserVisibleVersion", intern = TRUE)'
> system("cat /System/Library/CoreServices/SystemVersion.plist | grep -A 1 ProductUserVisibleVersion", intern = TRUE)
[1] "\t<key>ProductUserVisibleVersion</key>"
[2] "\t<string>12.6.1</string>"
```

This is still an issue in R-devel, btw:
```
❯ R-4.3 -q -e utils::osVersion
> utils::osVersion
[1] "macOS Big Sur ... 10.16"
```

**Comment by hueyrb** [comment] 2022-11-13 20:14
I don't understand why R 4.3 is doing that.  On my machine (with R4.2.2) --
I get Ventura, not Big Sur when I run  utils::osVersion in the console in
Rstudio or in R,

Are you suggesting I run the two scripts above? first one in Termina,
second in R?
[this is over my head


----------
Raymond B. Huey
***@***.***

**Comment by gaborcsardi** [comment] 2022-11-13 20:22
You have an Intel laptop, that is probably different. But yeah, if you run 
```
readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]
```
it will be probably different in a terminal (== quarto) and in RStudio, because macOS serves them different files.

**Comment by hueyrb** [comment] 2022-11-13 20:42
Here's what I get in R and in RStudio

readLines("/System/Library/CoreServices/SystemVersion.plist")[11:12]
[1] "\t<key>ProductUserVisibleVersion</key>"
[2] "\t<string>13.0.1</string>"

Thanks for persevering!

**Comment by gaborcsardi** [comment] 2023-10-31 18:27
Hopefully this is fixed now in newer R versions. In any case, it was a bug in `utils::sessionInfo()`, which we rely on. If it is not fixed, then please reopen this issue and we can try to implement a workaround in the sessioninfo package.

**Closed by gaborcsardi** 2023-10-31 18:27 UTC
